### ISSUE TITLE
Attempting to index a nil value

### ISSUE THREAD

**Issue by lFARVA** [meta-hub/fivem-drilling#1]
![ss+(2020-04-16+at+07 06 36)](https://user-images.githubusercontent.com/36070541/79514976-6aa3a700-8015-11ea-9c02-71c565684ad4.png)

**Comment by lFARVA** [comment]
I should note that this error persists - even with the meta_libs update from yesterday.

**Comment by meta-hub** [comment]
Forgot to reference meta_libs scaleforms. Fixed now.
